name: Pipeline CI dan CD

on:
  push:
    branches: [ main ]

jobs:
  proses-ci-dan-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari GitHub
        uses: actions/checkout@v4

      # --- INI PROSES CI (Pengecekan) ---
      - name: Install Alat Penguji HTML
        run: npm install -g htmlhint

      - name: Mulai Uji Semua File HTML
        run: htmlhint "**/*.html"

      # --- INI PROSES CD (Pengiriman ke Server) ---
      - name: Pasang Website Otomatis ke Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
