name: Check HTML files

on:
  push:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check HTML files
        run: test -f filerusak.html && test -f test.html
