name: Pengecekan Otomatis

on:
  push:
    branches: [ main ]

jobs:
  tes-codingan:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari GitHub
        uses: actions/checkout@v4

      - name: Install Alat Penguji HTML (HTMLHint)
        run: npm install -g htmlhint

      - name: Mulai Uji Semua File HTML
        run: htmlhint "**/*.html"
